### ISSUE TITLE
Minimum value is ignored

### ISSUE THREAD

**Issue by Arthur-Guillaume** [yonat/MultiSlider#10]
Hi,
Thanks for this good library.

I set a minimum and a maximum value to a horizontal slider with two thumbs.
I then set values for thumbs to the minimum and the maximum.

`
        self.slider.minimumValue = 45
        self.slider.maximumValue = 250
        self.slider.snapStepSize = 1
        self.slider.value = [45, 250]
`

When I start moving the dot to set a value, it starts from 0 which breaks the slider UI (the thumb stays stuck on the left until I move to 45 and starts moving after).

Moreover it allows the user to select a value I wanted to be forbidden.

Did I misunderstood something in the doc or is it a bug ? 

Thanks.

**Comment by yonat** [comment]
Seems like a bug, thanks for the report!
I'll check and see if I can fix it.

**Comment by yonat** [comment]
Fixed in 1.5.1.
