### ISSUE TITLE
run func at and of drag in SwiftUI

### ISSUE THREAD

**Issue by ahartman** [yonat/MultiSlider#101]
I see I tagged this as a bug but that is not my intention as I had it working. Sorry about that.

I have a question: how do I react to endOfDrag in SwiftUI?
.valueChanged and .touchUpInside give an error :'Value of type 'MultiValueSlider' has no member 'touchUpInside'

Regards, ahartman, Belgium

**Comment by yonat** [comment]
Hi @ahartman , please say more about what you are trying to achieve.
What will happen on the end of the drag?
What is the difference between it and setting `slider.isContinuous = false` ?

**Comment by ahartman** [comment]
Dear Yonat,

Thank you for your quick reaction.
In your README.md two events are mentioned: .valueChanged and .touchUpInside

I would like to react to .touchUpInside to run business logic with the new values  once the user ends dragging the slider.

Kind regards, ahartman, Belgium

**Comment by yonat** [comment]
Try setting `isContinuous` to `false` (in `MultiValueSlider` init) and then you can use `.onChange()`.

**Comment by ahartman** [comment]
Dear Yonat,

Thank you, that fixed the issue.

What is the difference between .isContinuous = false and snapStepSize?
snapStepSize makes the slider discontinuous as well in my opinion?

You might make your example fully SwiftUI and show the .onChange.
I would think nobody wants a slider for nothing, so it is essential to note endOfChange and be able to react to newly set values.

Tjaks again,

ahartman, belgium

**Comment by yonat** [comment]
`isContinuous` is the same as for the standard `UISlider` -- see [UISlider.isContinuous documentation](https://developer.apple.com/documentation/uikit/uislider/1621340-iscontinuous).

`onChange` is standard in SwiftUI -- see [SwiftUI onChange documentation](https://developer.apple.com/documentation/swiftui/view/onchange(of:perform:)).
