### ISSUE TITLE
PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by shahzadhussainios** [yonat/MultiSlider#102]
Please update with PrivacyInfo.xcprivacy. Otherwise, apple will not accept apps which uses MultiSlider

**Comment by yonat** [comment]
Already included since 2.1.1

**Comment by tkachV** [comment]
still have problem in Apple Privacy report. In are lib and dependency-libs.
<img width="834" alt="Screenshot 2024-04-05 at 2 15 43 PM" src="https://github.com/yonat/MultiSlider/assets/16904429/3b916bec-9a56-448c-903d-fd90b1e8564f">

**Comment by shahzadhussainios** [comment]
Same problem still i am facing

**Comment by tkachV** [comment]
@yonat Hello 👋, you will do something with it?

**Comment by yonat** [comment]
Thanks for reporting, fixed in 2.1.3.

**Comment by tkachV** [comment]
@yonat when fix will be compatible with cocoa pods?
<img width="565" alt="Screenshot 2024-04-08 at 11 50 51 AM" src="https://github.com/yonat/MultiSlider/assets/16904429/49891dbc-872a-44d0-b052-6f918f4e3521">

**Comment by yonat** [comment]
@tkachV done.

**Comment by tkachV** [comment]
@yonat Man, sorry but and still....)
<img width="914" alt="Screenshot 2024-04-10 at 4 28 09 PM" src="https://github.com/yonat/MultiSlider/assets/16904429/af08518c-e8be-4f6c-8b33-f53dd31c80a4">

**Comment by yonat** [comment]
Try:
`pod repo update`
`pod update MultiSlider`

**Comment by tkachV** [comment]
I know, I do  `pod install --repo-update`  and library updated to 2.1.3, now from 3 problem left only 1 in your old lib  https://github.com/yonat/AvailableHapticFeedback
<img width="340" alt="Screenshot 2024-04-10 at 5 08 52 PM" src="https://github.com/yonat/MultiSlider/assets/16904429/7d6ed74a-9451-48e7-9f70-85446a24bafc">

**Comment by yonat** [comment]
I totally forgot about this one! Removed this dependency, should be good now. (2.1.5)
