### ISSUE TITLE
SwiftUI slider implementation is not displayed correctly on iOS 16.1 simulator

### ISSUE THREAD

**Issue by kuzomenskyi** [yonat/MultiSlider#103]
**Description of the problem:**
I have added the slider on SwiftUI view but the view is not displayed correctly. The one thing displayed is the blue line, instead of the whole interface. It works fine with UIKit though.

**Minimal project that reproduces the problem (so I'll be able to figure out how to fix it):**
I have created the project specifically to reproduce the bug. Here is the link:
https://github.com/kuzomenskyi/MultiSliderIsNotDisplayedCorrectly

Here is how it looks like on Xcode Preview:
<img width="1249" alt="Screenshot 2024-04-11 at 11 23 01 AM" src="https://github.com/yonat/MultiSlider/assets/57143359/096e4124-ea17-4ba0-9fd6-9d83ba4b4891">

Here is how it looks like on Simulator:
<img width="371" alt="Screenshot 2024-04-11 at 11 23 07 AM" src="https://github.com/yonat/MultiSlider/assets/57143359/8ac7b7d8-e071-41eb-82e0-2f371f816673">

**Comment by kuzomenskyi** [comment]
Turns out that not only minimumValue and maximumValue should be provided with appropriate values, but the same is right for the value binding itself, which was not clear for me after reading the documentation. 

So I have forked the repo and created the pull request. Please, consider merging it:
https://github.com/yonat/MultiSlider/pull/104

Thanks!

**Comment by yonat** [comment]
True, if you set empty `value`, it means zero thumbs will be shown - this is the expected behavior.
