### ISSUE TITLE
Build on xcode 9.4.1

### ISSUE THREAD

**Issue by niloufarMakhzani** [yonat/MultiSlider#14]
I'm trying to run the example source code in xocde version 9.4.1 but I get errors like this " 'Attribute' is not a member type of 'NSLayoutConstraint' , 'Relation' is not a member type of 'NSLayoutConstraint' " in it's miniLayout class.

**Comment by yonat** [comment]
Use version 1.6.0:

```ruby
pod 'MultiSlider', '~> 1.6.0'
```

**Comment by niloufarMakhzani** [comment]
I tried that as well but still get same errors

**Comment by yonat** [comment]
Ah, then put this in your `Podfile`:

```ruby
pod 'MiniLayout', '~> 1.2.1'
pod 'MultiSlider', '~> 1.6.0'
```

Then do `pod update` and try again.

**Comment by niloufarMakhzani** [comment]
[!] CocoaPods could not find compatible versions for pod "MiniLayout":
  In snapshot (Podfile.lock):
    MiniLayout (= 1.3.0)

  In Podfile:
    MiniLayout (~> 1.2.1)

Specs satisfying the `MiniLayout (~> 1.2.1), MiniLayout (= 1.3.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by yonat** [comment]
Is that after a `pod install`? If so, try `pod update`.

**Comment by niloufarMakhzani** [comment]
Done, but still get same error:

"'Attribute' is not a member type of ‘NSLayoutConstraint'"

**Comment by yonat** [comment]
Hmmm. Just to make sure, please re-build.
Also, could you paste your `Podfile.lock`?

**Comment by niloufarMakhzani** [comment]
Figured out, but now when I run I get “EXC_BAD_ACCESS” on this line:

    slider.minimumValue = 1

**Comment by yonat** [comment]
Do you use a storyboard/xib? Is the outlet correctly connected to `slider`?

**Comment by niloufarMakhzani** [comment]
Yes and its connected correctly

**Comment by yonat** [comment]
What happens if do a different operation on `slider`?
For example, try `slider.tintColor = .cyan` or something similar.

**Comment by niloufarMakhzani** [comment]
That line works correctly but crashes on setting min value

**Comment by yonat** [comment]
Not sure what is the problem. Maybe try to set `slider.value` first (to something greater than 1) and see what happens.

**Comment by niloufarMakhzani** [comment]
Dear Yonat

Thanks for your help. Actually I’m trying to have a vertical slider so I can have filters on price. I found your project and I’m trying to customize it to suits my case.

I think I’m eating your time, I will try my best to make it work, I will contact you later id I need help 🙏🏻

**Comment by yonat** [comment]
Good luck!
