### ISSUE TITLE
horzontal slider 

### ISSUE THREAD

**Issue by kavin06** [yonat/MultiSlider#17]
*** Assertion failure in -[NSLayoutConstraint _setMultiplier:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1562/Foundation/Layout.subproj/NSLayoutConstraint.m:196
2019-03-11 12:39:32.198830+0530 DCON[3784:1325822] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Multiplier is not finite!  That's illegal.  multiplier:inf'

Application crashed. ios 12 horizontal and vertical slider is not working any help

**Comment by yonat** [comment]
Hi @kavin06,
I'm not able to reproduce this error. Can you write the minimal code to reproduce it?
(I.e., create a new blank project, add MultiSlider, and write code that produces this error -- so I can check it.)

Thanks!

**Comment by kavin06** [comment]
Hi @yonat ,
I used lower version so I faced that issue, kindly ignore this issue. I need to set fixed distance between two Thumbs?  
 thanks in advance

**Comment by yonat** [comment]
```swift
slider.snapStepSize = 0.5 // or whatever value you need
```
