### ISSUE TITLE
Issue when placing MultiSlider in tableview cell

### ISSUE THREAD

**Issue by WedgeSparda** [yonat/MultiSlider#19]
Hi.

I have an issue with this slider. I'm using several MultiSliders in a tableview but when I try to scroll it, If my pan gesture  starts on one of the MultiSliders, the gesture is captured by the slider and scroll doesn't work until I start panning from outside the sliders.

Is there any possibility to improve the slider to propagate the pan to superview if we needed?

Thanks.

**Comment by yonat** [comment]
Setting `cancelsTouchesInView` will probably solve it.
If it works for you, feel free to submit a PR.
If not, please write a minimal app the reproduces this problem, so I can check it.

**Comment by WedgeSparda** [comment]
I downloaded the source code and modified the `setupPanGesture` method like this:

```
    private func setupPanGesture() {
        addConstrainedSubview(panGestureView)
        for edge: NSLayoutConstraint.Attribute in [.top, .bottom, .left, .right] {
            constrain(panGestureView, at: edge, diff: -edge.inwardSign * margin)
        }
        let panGesture = UIPanGestureRecognizer(target: self, action: #selector(didDrag(_:)))
        panGesture.cancelsTouchesInView = false
        panGestureView.addGestureRecognizer(panGesture)
    }
```

But didn't work :(

So I created this [test project](https://github.com/WedgeSparda/MultiSlider-IssueTest) so you can see what happens. As you can see, if scroll drag starts on one of the labels, it works fine, but if starts on one of the multisliders, then scroll doesn't happen.

Hope you can point me in the right direction.

Thanks.

BTW: Great job with this library.

**Comment by yonat** [comment]
Thanks for test project, it helped me solve this!
