### ISSUE TITLE
Values become weird if the thumbs overlap

### ISSUE THREAD

**Issue by Sweeper777** [yonat/MultiSlider#2]
I used these settings:

<img width="254" alt="2017-05-14 8 10 30" src="https://cloud.githubusercontent.com/assets/13585047/26031923/d808a086-387c-11e7-917a-7bacd6ffce74.png">

I slid all the thumbs to the bottom such that they can't be moved downwards anymore. Then I saw some weird values. From the value of the lowest thumb to the value of the highest thumb is the following values:

0.0, 0.999999999999986, 1.99009900990099, 2.98019801980197, 3.97029702970296

I would like the values to either be all 0s or rounded up to 0, 1, 2, 3, 4. Can you fix this?

**Comment by yonat** [comment]
Thanks, fixed in 1.1.2.
