### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by Anavrin1990** [yonat/MultiSlider#21]
Hello, in UITableViewCell constraints break

**Comment by yonat** [comment]
Thanks for reporting!
If you have a fix -- please submit a PR.
If not, please create a minimal project that exhibits this problem, so I can fix it.

**Comment by Anavrin1990** [comment]
You should just add a multiSlider to tableView cell and you will see. To resolve issue you can use anchors in your layout instead of miniLayout pod, which use constraints. --Отправлено из мобильной Яндекс.Почты21.03.2019, 23:20, "Yonat Sharon" <notifications@github.com>:Thanks for reporting!
If you have a fix -- please submit a PR.
If not, please create a minimal project that exhibits this problem, so I can fix it.

**Comment by yonat** [comment]
Thanks, seems you already know how to fix this - please submit a PR with Example code that exhibits the problem. Thanks!

**Comment by yonat** [comment]
Closing because of total lack of code to demonstrate the problem or solution.
