### ISSUE TITLE
Error when both thumb views are on the same value

### ISSUE THREAD

**Issue by BrandonCao** [yonat/MultiSlider#22]
When both thumbs are on the same value, the lower bound one cannot slide back down

**Comment by BrandonCao** [comment]
Snap value: 1
Min : 1
Max: 7 

Both thumbs at value 6, trying to slide lower bound to value 5.

**Comment by yonat** [comment]
@BrandonCao How did you get them both to 6? They can't be dragged there by the user...

If you did it in code (e.g. `slider.value = [6, 6]`) then may I ask what is the use case? It doesn't seem to make sense to put two thumbs on the same value.

**Comment by BrandonCao** [comment]
I set 

`keepsDistanceBetweenThumbs = false`

Our use case was allowing the users to select a range but give them the option to limit it to one value. After messing around with it, it might be best to go a different route UX wise.

**Comment by christianArby** [comment]
@yonat Why did you close this issue? It makes perfect sense in a lot of use cases to have the both thumbs on the same value, e.x. when setting a price range and you want to set the min price to the max price or max price to free.

**Comment by yonat** [comment]
Got it. Fixed in 1.9.8.

**Comment by christianArby** [comment]
Thank you, i will try the new version!
