### ISSUE TITLE
Slider track gets aligned to top of UIView

### ISSUE THREAD

**Issue by vaibhavarora03** [yonat/MultiSlider#24]
I am facing an issue where the slider track gets aligned to the top of the UIView. Has anyone faced such issue? I am attaching the screenshots of the MultiSliders along with UIDebugger screenshot. TIA.

The UIView is vertically centered to UIImageView with horizontal spacing.

![Screen Shot 2019-04-15 at 5 49 44 PM](https://user-images.githubusercontent.com/47171140/56132217-0c2d8e00-5fa7-11e9-9465-ae18bdb75b62.png)
![Screen Shot 2019-04-15 at 5 50 11 PM](https://user-images.githubusercontent.com/47171140/56132224-0e8fe800-5fa7-11e9-9968-dec3750bd175.png)
![Screen Shot 2019-04-15 at 5 50 18 PM](https://user-images.githubusercontent.com/47171140/56132227-118ad880-5fa7-11e9-8c50-af75ced0a63a.png)

This is the screenshot of UIDebugger.

![Screen Shot 2019-04-15 at 5 53 17 PM](https://user-images.githubusercontent.com/47171140/56132366-6890ad80-5fa7-11e9-8bf4-7efb4a6d8bda.png)

**Comment by yonat** [comment]
@vaibhavarora03 The best way for me to help is if you create a minimal project that reproduces the problem, and post the code. Preferably create a new repo link to it here.

**Comment by vaibhavarora03** [comment]
Sure. I'll update here ASAP.

**Comment by vaibhavarora03** [comment]
@yonat I've mentioned the link to the public repo below. The issue has been reproduced in it. Kindly check it. Thanks

https://github.com/vaibhavarora03/MultiSliderIssue

**Comment by Punitbansal** [comment]
i am also facing the issue on iOS 12.1.

**Comment by vaibhavarora03** [comment]
@yonat I ran the project with issue on device with OS 11.2.2 and I have attached its screenshots below. Its running fine on this particular version. When run on device or simulator with OS 12.0 or above the issue remains the same.

![IMG-0489](https://user-images.githubusercontent.com/47171140/56187868-8f9bbd80-6041-11e9-8d75-ae1fb44a6fc5.PNG)

![IMG-0488](https://user-images.githubusercontent.com/47171140/56187873-91fe1780-6041-11e9-8ca0-e902e9beab79.PNG)

**Comment by Punitbansal** [comment]
Check it on 12.1.

**Comment by Punitbansal** [comment]
I am getting one error while using it in storyboard.
<img width="495" alt="Screen Shot 2019-04-16 at 12 25 22 PM" src="https://user-images.githubusercontent.com/8542747/56188351-ea81e480-6042-11e9-9d83-d5b740726beb.png">

**Comment by vaibhavarora03** [comment]
@Punitbansal I also get the same error but somehow on running the app the issue doesn't replicate in OS 11.2.2.

**Comment by Punitbansal** [comment]
The issue happens on ios 12.1

**Comment by yonat** [comment]
Pushed 1.9.2 with an iOS 12 workaround.

**Comment by nbansal2211** [comment]
Thanks @yonat .

**Comment by vaibhavarora03** [comment]
Thanks @yonat.
