### ISSUE TITLE
AvailableHapticFeedback Library image not found

### ISSUE THREAD

**Issue by mkonopka9418** [yonat/MultiSlider#25]
After installing the MultiSlider library by including pod 'MultiSlider' in my Podfile I receive the following error when attempting to set the class of a view to MultiSlider in my storyboard:

file:///Users/michellelane/ios-app/Spyderco/Spyderco/Settings/Storyboards/SettingsTermsAndConditions.storyboard: error: IB Designables: Failed to render and update auto layout status for UIViewController (sky-2X-3GA): dlopen(MultiSlider.framework, 1): Library not loaded: @rpath/AvailableHapticFeedback.framework/AvailableHapticFeedback
  Referenced from: MultiSlider.framework
  Reason: image not found

Any thoughts on why this might occur?

**Comment by yonat** [comment]
I get this error sometimes in Interface Builder, but the app seems to work just fine. Don;t know hoe to solve it, sorry,

Does the app work for you when you run it?
