### ISSUE TITLE
Setting different UIImageViews for each thumbImage

### ISSUE THREAD

**Issue by wammy67** [yonat/MultiSlider#27]
it just keeps crushing when trying to assign:

`self.multiSlider.thumbViews = [imageView1,imageView2,imageView3]`

it gives

 'Unable to install constraint on view.  Does the constraint reference something from outside the subtree of the view?' 

I've tried adding imageviews to view hierarchy to main view and even multislider

**Comment by wammy67** [comment]
can't we just have UIViews instead of UIImageViews? otherwise library works cool :)

**Comment by yonat** [comment]
You can try this instead:

```swift
multiSlider.thumbViews[0].image = image1
multiSlider.thumbViews[1].image = image2
multiSlider.thumbViews[2].image = image3
```

**Comment by wammy67** [comment]
sounds good, doesn't work

slider hasn't changed at all.
I've made some changes and made it work, I'll try to contribute 👍 👍

**Comment by yonat** [comment]
Works for me, see the demo project in branch [thumb-images](https://github.com/yonat/MultiSlider/blob/99fe64066e9d6c99e9baa18d68be3030c16dfcb1/Example/MultiSliderDemo/ViewController.swift#L45)
