### ISSUE TITLE
Adjusted value bug

### ISSUE THREAD

**Issue by invertercant** [yonat/MultiSlider#28]
**Description of the problem:**
Wrong upperBound when you snapStepSize is set
For example:
multiSlider.snapStepSize = 100.0
multiSlider.value = [40645.0, 81645.0]
This function  - adjustValuesToStepAndLimits() define upperBound wrong.
For my case it will be transformed to [40645.0, 81600.0]
I expected to get the same values as input.
As a result when I get values after user selection I get cutting upper edge

**Comment by yonat** [comment]
`snapStepSize` is only for dragging the thumbs by users, not for programmatically changing the `value`. If you change the `value` programmatically then it's up to you to decide if you want it to snap or not.
