### ISSUE TITLE
Add slider value text on thumb image.

### ISSUE THREAD

**Issue by Pankaj03** [yonat/MultiSlider#29]
**Description:**
I need to add slider value like 50 on the individual thumb image.

Can you please help, how can i do that.

Thanks!

![RangeSlider](https://user-images.githubusercontent.com/4309635/61798679-585e5900-ae47-11e9-90f2-ce1b701480f7.png)

**Comment by yonat** [comment]
But the thumb is, well, under the user's thumb -- the user doesn't see the label on it!

Instead you can do:

```swift
slider.valueLabelPosition = .top
```

Then the value will be above the thumb, where the user can see it.

**Comment by Pankaj03** [comment]
Hi @yonat,
   
Thanks for your quick response!

You're right that the text will not be viewed under user's thumb.
But now, i have customised your lib and achieved what i want. 
Thanks for creating this useful lib.

Thanks!
