### ISSUE TITLE
Allow thumbs to cross over each other

### ISSUE THREAD

**Issue by dfr4** [yonat/MultiSlider#30]
This is a great library. I was wondering if it's possible to allow thumbs to cross over each other? Is this already a feature?
Allowing the left thumb go over the right thumb or allowing the right thumb go over the left thumb. Please let me know if this hasn't been implemented yet, thank you.

**Comment by dfr4** [comment]
I solved this by forking the repository and changing this MultiSlider+Drag.swift line 59 for 

```
let bottomLimit = draggedThumbIndex > 0
            ? slideView.bounds.bottom(in: orientation)
            : slideView.bounds.bottom(in: orientation)
let topLimit = draggedThumbIndex < thumbViews.count - 1
            ? slideView.bounds.top(in: orientation)
            : slideView.bounds.top(in: orientation)
```

**Comment by yonat** [comment]
Nice, you can go even shorter:

```swift
let bottomLimit = slideView.bounds.bottom(in: orientation)
let topLimit =  slideView.bounds.top(in: orientation)
```

(Though I'll keep this repo without this change, because I think most users don't want thumbs to cross.)

**Comment by dfr4** [comment]
That makes sense. No problem, thank you!

**Comment by mikhail-kuzmenko-hhl** [comment]
Also searched for such option, maybe add this feature as a property in future.
