### ISSUE TITLE
Cannot move the thumb

### ISSUE THREAD

**Issue by jn8029** [yonat/MultiSlider#35]
**Description of the problem:**
macOS Mojave 10.14.6
XCode 11.0
Simulator: iPhone 11 Pro Max (iOS 13.0) 
Cannot move any thumb on the slider.

**Minimal project that reproduces the problem (so I'll be able to figure out how to fix it):**
https://gist.github.com/jn8029/a61bc7f0eb106bc5e71082b1536088d1

<img width="349" alt="Screen Shot 2019-11-26 at 4 17 07 pm" src="https://user-images.githubusercontent.com/44837996/69611206-40524c80-1068-11ea-8531-01ff30fa0774.png">

**Comment by yonat** [comment]
Make sure your `containerView` size is not 0 -- add the following line to `setupContainerView()`:

```swift
containerView.bottomAnchor.constraint(equalTo: view.safeAreaLayoutGuide.bottomAnchor, constant: -30).isActive = true
```

**Comment by jn8029** [comment]
apologies for my newbie issue!

**Comment by yonat** [comment]
No problem, you phrased the issue very well.
