### ISSUE TITLE
Initial value doesnot show positiveSuffix

### ISSUE THREAD

**Issue by shubham14896** [yonat/MultiSlider#36]
**Description of the problem:**
[description]

**Minimal project that reproduces the problem (so I'll be able to figure out how to fix it):**
[github repo or a zipped project]

**Comment by yonat** [comment]
Good catch!
Fixed in version 1.10.2.

**Comment by jstoppenbach** [comment]
This update introduces a crash with iOS 10.

**Comment by yonat** [comment]
True. It seems `removeObserver()` is  completed only after the old formatter is discarded, and not synchronously.

I disabled the fix for iOS < 11, so in 1.10.4 you will have neither the crash nor the fix on old iOS versions.
