### ISSUE TITLE
Disable Half Thumb Protruding outside Track

### ISSUE THREAD

**Issue by akahnn** [yonat/MultiSlider#37]
**Description:**
Is there a simple way to disable half the thumb protruding outside of its track? I want the end of the thumb to align perfectly with the end of the track.

**Comment by yonat** [comment]
It's an old problem that I wasn't able to solve, introduced back in iOS 12β. I was hoping it would get fixed by Apple, but it seems I need to write a workaround instead.

Version 1.10.3 has the fix.

**Comment by akahnn** [comment]
Thanks for the speedy reply! @yonat 

What I wanted was the blue and pink to align perfectly on maximum ends.  In `1.10.3` it instead leaves the track visible in the image un0slidable and the thumb doesn't ever cover it. 
  
![IMG_0759](https://user-images.githubusercontent.com/4313836/73152498-f0d4df00-40f1-11ea-9472-b7ac4cfae49f.PNG)
