### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by reybriel** [yonat/MultiSlider#39]
**Description:**
You currently do not have support for Carthage.

**Problems I encountered when trying to implement this myself:**
I'm working in a project where we are trying to remove the cocoapods, and we've moved all our libs to Carthage. 

We would like to use your lib without the need to use cocoapods.

**Comment by yonat** [comment]
Sorry, I don't use Carthage myself so it's out of my scope. But if you submit a pull request with Carthage support I would be happy to merge it.

**Comment by yonat** [comment]
Closing, as I don't expect to ever support Cartage now with spm.
