### ISSUE TITLE
2 Storyboard errors

### ISSUE THREAD

**Issue by Sweeper777** [yonat/MultiSlider#4]
I got 2 storyboard errors when I added a slider into the storyboard. They are:

> error: IB Designables: Failed to render and update auto layout status for MyViewController (X4n-4q-1cD): dlopen(MultiSlider.framework, 1): Library not loaded: @rpath/MiniLayout.framework/MiniLayout
  Referenced from: MultiSlider.framework
  Reason: image not found

> error: IB Designables: Failed to update auto layout status: dlopen(MultiSlider.framework, 1): Library not loaded: @rpath/MiniLayout.framework/MiniLayout
  Referenced from: MultiSlider.framework
  Reason: image not found

It's not affecting compilation though. How can I get rid of them?

**Comment by yonat** [comment]
It's in my [TODO list](https://github.com/yonat/MultiSlider#todo)...

**Comment by kavin06** [comment]
Hai @yonat ,
error: IB Designables: Failed to update auto layout status: dlopen(MultiSlider.framework, 1): Library not loaded: @rpath/MiniLayout.framework/MiniLayout
Referenced from: MultiSlider.framework
Reason: image not found

I didn't find anything in TODO list... any help

**Comment by yonat** [comment]
Sorry, I don't have a solution right now. If you find a fix, please submit a PR!
