### ISSUE TITLE
Change the center of the thumb outside

### ISSUE THREAD

**Issue by ManituPC** [yonat/MultiSlider#40]
**Description:**
Add possibility of change the center of the thumb outside. Some like @IBInspectable or public. I couldn’t do the native behavior of the thumb as in Settings in iPhone on the “Brightness” slider

**Comment by yonat** [comment]
What do you mean? Something to do with `minimumImage` and `maximumImage`? Something to do with `thumbImage`? Something else?

**Comment by ManituPC** [comment]
@yonat yes. Now the center of the thumb image, at the edge position, is the minimum or maximum track value. And I can’t do this so that the thumb does not go beyond the minimum or maximum value of the track. For example, the right edge of the thumb in the extreme position will be at one point with the maximum track value

**Comment by ManituPC** [comment]
<img width="693" alt="slider" src="https://user-images.githubusercontent.com/28258464/74656980-f7f28880-5197-11ea-9c60-34eac4a13240.png">

**Comment by ManituPC** [comment]
sorry! I see you solved this problem here https://github.com/yonat/MultiSlider/issues/37
