### ISSUE TITLE
Different image for each thumb

### ISSUE THREAD

**Issue by b7anka** [yonat/MultiSlider#43]
Hello, firstly let me thank you guys for this awesome range slider component, and then let me ask you guys if you could make a feature that allows to give each thumb it's own image.

Thank you in advance

**Comment by yonat** [comment]
Try this:

```swift
multiSlider.thumbViews[0].image = #imageLiteral(resourceName: "firstThumb.png")
multiSlider.thumbViews[1].image = #imageLiteral(resourceName: "secondThumb.png")
```

**Comment by b7anka** [comment]
> Try this:
> 
> ```swift
> multiSlider.thumbViews[0].image = someImage
> multiSlider.thumbViews[1].image = anotherImage
> ```

thank you very much it works flawlessly!
