### ISSUE TITLE
In case of two thumbs, the second thumbs fluctuates on sliding the first thumb

### ISSUE THREAD

**Issue by vikash213** [yonat/MultiSlider#44]
**I am using the Multislider pod and when I choose to use two thumb and I tried to move the first thumb then right thumb automatically fluctuates **
[description]

**Minimal project that reproduces the problem (so I'll be able to figure out how to fix it):**
[github repo or a zipped project]

**Comment by yonat** [comment]
@vikash213 please create a minimal project that reproduces the problem and link to the repo, so I can see the problem and fix it.

**Comment by yonat** [comment]
@vikash213  Still a problem? To help me help you, please create a minimal reproducible project:

1. Fork this repo. (See [instructions](https://guides.github.com/activities/forking/))
2. Open the project in the `Example` directory.
3. Change the code there to make the problem appear.

Then just link to your fork here.
