### ISSUE TITLE
setting different images to individual thumb

### ISSUE THREAD

**Issue by vittalk** [yonat/MultiSlider#45]
Hi, 
I would like to assign a different image to each individual thumb. I want to have a slider that has 3 thumbs. The left and right thumbs are my start and end thumbs, while the middle thumb is a progress thumb to show the progress of an audio/video player.  I would like have the start and end thumbs have a different image while the middle progress thumb will different image.  Please let me know if this is already available ? or how would I implement them.

thanks,
-Vittal
email-dot-vittal-at-gmail-dot-com

**Comment by yonat** [comment]
Added the explanation to https://github.com/yonat/MultiSlider#images :

```swift
slider.thumbViews[0].image = UIImage(named: "ball")
slider.thumbViews[1].image = UIImage(named: "club")
```
