### ISSUE TITLE
Need to set distance between to sliders to a minimum of 4 but can't

### ISSUE THREAD

**Issue by michaeldebo** [yonat/MultiSlider#49]
ageSlider.distanceBetweenThumbs = 4 causes my app to crash every time. I do not understand why or what to do to get a minimum distance of 4 between my two sliders. Crash report says the following:

2020-04-30 18:18:45.152808-0400 Revibe[14213:2645545] -[MultiSlider.MultiSlider setDistanceBetweenThumbs:]: unrecognized selector sent to instance 0x7fbedc95c820
2020-04-30 18:18:45.164995-0400 Revibe[14213:2645545] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MultiSlider.MultiSlider setDistanceBetweenThumbs:]: unrecognized selector sent to instance 0x7fbedc95c820'

**Comment by yonat** [comment]
Hi @michaeldebo , please link to a minimal project that reproduces the problem. It’s very hard to fix a problem I can’t reproduce...

**Comment by michaeldebo** [comment]
I don't know how to produce a link to it, but here is all the relevant code for the slider:

    private func configureAgeSlider() {
        let age = ProfileDataManager.shared.age
        var lowValue: CGFloat = 18
        if age - 8 > 18 {
            lowValue = CGFloat(age - 8)
        }
        ProfileDataManager.shared.minAge = Int(lowValue)
        var highValue: CGFloat = 90
        if age + 8 < 90 {
            highValue = CGFloat(age + 8)
        }
        ageSlider.minimumValue = 18
        ageSlider.maximumValue = 90
        ageSlider.value = [lowValue, highValue]
        ageSlider.orientation = .horizontal
        ageSlider.tintColor = UIColor.convertHexColor(hex: "efefef")
        ageSlider.thumbImage = UIImage(named: "slider")!
        ageSlider.trackWidth = 3
        ageSlider.showsThumbImageShadow = false
        ProfileDataManager.shared.maxAge = Int(highValue)
        ageSlider.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(ageSlider)
        let verticalOffset = getSize(large: 80, medium: 60, small: 45)
        ageSlider.topAnchor.constraint(equalTo: distanceSlider.bottomAnchor, constant: verticalOffset).isActive = true
        ageSlider.leftAnchor.constraint(equalTo: letsNarrowItDownLabel.leftAnchor).isActive = true
        ageSlider.rightAnchor.constraint(equalTo: letsNarrowItDownLabel.rightAnchor).isActive = true
        ageSlider.heightAnchor.constraint(equalToConstant: 30).isActive = true
        ageSlider.addTarget(self, action: #selector(ageSliderChanged(_:)), for: .valueChanged)
        addAgeLabel()
        addAgeTitleLabel()
        addMinimumAgeLabel()
        addMaximumAgeLabel()
    }

    @objc func ageSliderChanged(_ ageSlider: MultiSlider) {
        print("thumb \(ageSlider.draggedThumbIndex) moved")
        print("now thumbs are at \(ageSlider.value)")
        ageSlider.keepsDistanceBetweenThumbs = true
        ageSlider.distanceBetweenThumbs = 4
        ageLabel.text = "\(Int(ageSlider.value[0])) - \(Int(ageSlider.value[1]))"
        ProfileDataManager.shared.minAge = Int(ageSlider.value[0])
        ProfileDataManager.shared.maxAge = Int(ageSlider.value[1])
        print("Range slider value changed: \(ageSlider.value)")
    }

**Comment by yonat** [comment]
Please provide code I can execute to reproduce  the problem, without calling functions that I don't have the code to. See https://stackoverflow.com/help/minimal-reproducible-example for instructions on how to create such code.

I really want to help, but I can't fix what I can't reproduce.

**Comment by yonat** [comment]
Okay, had some time so I did that for you. I don't get a crash... Here is the code I added to the Example project found in this repo, based on your code:

```swift
    private func configureAgeSlider() {
        let ageSlider = MultiSlider()
        ageSlider.minimumValue = 18
        ageSlider.maximumValue = 30

        let age: CGFloat = 50
        let lowValue = max(ageSlider.minimumValue, age - 8)
        let highValue = min(ageSlider.maximumValue, age + 8)
        ageSlider.value = [lowValue, highValue]

        ageSlider.orientation = .horizontal
        ageSlider.tintColor = .red
        ageSlider.trackWidth = 3
        ageSlider.showsThumbImageShadow = false
        ageSlider.addTarget(self, action: #selector(ageSliderChanged(_:)), for: .valueChanged)
        view.addConstrainedSubview(ageSlider, constrain: .leftMargin, .rightMargin)
        view.constrain(ageSlider, at: .top, to: multiSlider, at: .bottom, diff: 16)

        ageSlider.valueLabelPosition = .top
        ageSlider.distanceBetweenThumbs = 4
    }

    @objc func ageSliderChanged(_ ageSlider: MultiSlider) {
        print("thumb \(ageSlider.draggedThumbIndex) moved")
        print("now thumbs are at \(ageSlider.value)")
        print("Range slider value changed: \(ageSlider.value)")
    }
```

(Plus calling `configureAgeSlider()` from the end of `viewDidLoad()`)

**Comment by michaeldebo** [comment]
Ahh, so I can't use autolayout, no "translatesAutoresizingIntoConstraints = false" and it should work. Got it. Thanks for your help!

**Comment by yonat** [comment]
Auto layout works fine: `view.addConstrainedSubview()` sets `translatesAutoresizingIntoConstraints` to `false` internally.

**Comment by michaeldebo** [comment]
I needed to specify ageSlider.valueLabelPosition and it works. That's what my code was missing. Thx
