### ISSUE TITLE
Gap at the end of sliders

### ISSUE THREAD

**Issue by mkifetew2** [yonat/MultiSlider#50]
**Description of the problem:**
[description]

I have added a UIImage to each thumb in the MultiSlider but when I drag either the left thumb to the most minimum value or the right thumb to the most maximum value, it leaves a gap. So I thought if I increase the image size then I would solve that issue, what actually happened is the gap became bigger on both sides 

**Minimal project that reproduces the problem (so I'll be able to figure out how to fix it):**
[github repo or a zipped project]
<img width="278" alt="Screen Shot 2020-05-14 at 11 30 56 AM" src="https://user-images.githubusercontent.com/27515809/81954548-fd187580-95d6-11ea-9488-04a661c20649.png">
<img width="278" alt="Screen Shot 2020-05-14 at 11 32 54 AM" src="https://user-images.githubusercontent.com/27515809/81954550-fdb10c00-95d6-11ea-8cff-d29542f856e1.png">

**Comment by yonat** [comment]
Please ensure the thumb image doesn't have any transparent pixels on on the sides.

**Comment by mkifetew2** [comment]
It doesn't, I tried the same image on a native UISlider and it doesn't happen

**Comment by yonat** [comment]
Works fine for me. Please create a minimal project that reproduces the problem and link to it here. (see https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by yonat** [comment]
@mkifetew2 Still a problem? To help me help you, please create a minimal reproducible project:

1. Fork this repo. (See [instructions](https://guides.github.com/activities/forking/))
2. Open the project in the `Example` directory.
3. Change the code there to make the problem appear.

Then just link to your fork here.

**Comment by vuralcelik** [comment]
```
    private func changeThumbSizes() {
        multiSlider.thumbViews.forEach { imageView in
            imageView.image = UIImage(named: "sampleProfile")
            imageView.heightAnchor.constraint(equalToConstant: 40).isActive = true
            imageView.widthAnchor.constraint(equalToConstant: 40).isActive = true
            imageView.contentMode = .scaleToFill
        }
    }
```

Try to change images like that, it works fine for me. Looks like thumbImage property has a problem.
