### ISSUE TITLE
Constraint margins becoming mutable.

### ISSUE THREAD

**Issue by emtjoshhart** [yonat/MultiSlider#54]
**Unable to change the margin by which the MultiSlider sits within.**
Right now that value is 32:
`    let margin: CGFloat = 32`

 Should be able to change the padding around the slider with constants that the developer is okay with.

**Problems I encountered when trying to implement this myself:** Had to unlock file from cocoa pods in order to change it.

**Comment by yonat** [comment]
This `margin` property is not used for changing the padding, but only internally to catch dragging gestures. So you don't need to use it.

To set padding around the control, use the same constrains you would use with any other view.
