### ISSUE TITLE
Unknown class MultiSlider in Interface Builder file

### ISSUE THREAD

**Issue by hendyevan** [yonat/MultiSlider#55]
I use multi slider from xib. Create UIView and set class and module to MultiSlider.
But after i run, my app crash and got an error `Unknown class MultiSlider in Interface Builder file.`

**Comment by yonat** [comment]
When I do that it works fine...
Please create a minimal project that reproduces this problem, create a github project with its code, and link to it here. (See https://ootips.org/yonat/repex/)

**Comment by hendyevan** [comment]
The issue is solved, turn out i have to disable `isVertical`. Now it's working. Thanks for your feedback @yonat
