### ISSUE TITLE
overlapping thumbs 

### ISSUE THREAD

**Issue by belalmedhat97** [yonat/MultiSlider#56]
i made a year slider with 2 thumbs indicating start year and current year but when app launch thumbs are overlapped i want year slider to be like price slider 
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-22 at 03 37 19](https://user-images.githubusercontent.com/51267587/88124372-408df200-cbcd-11ea-85a1-50e738c7c756.png)

**Comment by yonat** [comment]
I'll need some code to help with this...
Please create a minimal project that reproduces this problem, create a github project with its code, and link to it here. (See https://ootips.org/yonat/repex/)

**Comment by belalmedhat97** [comment]
solved the issue
===> by defining attributes of slider using storyboard with attributes inspector 
### problem occur when define attributes programmatically
