### ISSUE TITLE
Remove dependencies (esp. SweeterSwift)

### ISSUE THREAD

**Issue by fl034** [yonat/MultiSlider#57]
Hey there, first of all thanks for your decent work here!

My request is to remove SweeterSwift and replace calls to it with native code.
When using Cocoapods SweeterSwift is available through all my project and is polluting my code completion box.
Certainly the stuff of SweeterSwift is super handy, but I don't want to use them to reduce dependencies from third party libraries.

**Comment by yonat** [comment]
What errors are you seeing?

**Comment by fl034** [comment]
No errors. It's just that when I code, I get all the auto-completion suggestions from SweeterSwift, which is a dependency of MultiSlider. And this I don't want, because when I or my colleagues use this stuff, we will be dependent on a library without really noticing.

My proposal would be to copy those functions you used from SweeterSwift and paste it as private functions in MultiSlider.

But I can also understand if you don't agree with me ☮️

**Comment by yonat** [comment]
I use SweeterSwift on many projects and libraries, doesn't make sense to maintain different copies for each one. Sorry.
