### ISSUE TITLE
SweeterSwift problem

### ISSUE THREAD

**Issue by dave-w3w** [yonat/MultiSlider#58]
**Description of the problem:**
This isn't really a 'bug' but it's not really a feature request either.  More accurately, it's an "issue"
https://github.com/SweeterSwift/Sweeter/issues/2
Sweeter includes the follow code which overrides any property accessed as an optional named 'value'.  UIKit has a lot of objects with a 'value' property.
extension Optional: Optionable {
public var value: Wrapped? { return self }
}

**Minimal project that reproduces the problem (so I'll be able to figure out how to fix it):**
Instantiate a UIStepper into an optional, and inspect its 'value' property, Xcode code complete will likely show two 'value' properties, one the expected value, and the other 'self'.

Consider using a different library than Sweeter, or encourage them to change this.

**Comment by yonat** [comment]
Do you get an actual error?
When I write code to test this, it passes fine:

```swift
    func testOptionableValue() {
        let optionalStepper: UIStepper? = UIStepper()
        optionalStepper?.value = 42
        XCTAssertEqual(optionalStepper?.value, 42)
    }
```

Would you provide code that reproduces the problem your are seeing? (See https://ootips.org/yonat/repex/)

**Comment by dave-w3w** [comment]
Hi, I swear it wasn't working for me on Friday, but I can't replicate it now, and seems to be working fine. It does create a little confusion with autocomplete however (see attached) if the optional isn't dereferenced correctly.  Sorry to trouble you.
![image](https://user-images.githubusercontent.com/46780785/92390499-de546680-f112-11ea-97e8-7dc1413cf313.png)

**Comment by yonat** [comment]
Glad it's working for you!
I'll probably rename it to avoid the confusion, though. Thanks for reporting.
