### ISSUE TITLE
None of the releases contain the swiftUI MultiValueSlider

### ISSUE THREAD

**Issue by JKim0119** [yonat/MultiSlider#61]
**Description of the problem:**
When doing a `pod install`, the MultiValueSlider is not present. The releases do not contain the MultiValueSlider.swift file in the sources. I assume this is because the releases are created from the master branch. 

I'd like to see a release with the swiftUI branch or merging the swiftUI branch into the master branch.

Only way to get MultiValueSlider into project is to clone the repo and branch to the swiftUI branch and set the MultiSlider pod path to the repo path.

Thanks!

**Comment by yonat** [comment]
Try this:

```ruby
pod 'MultiSlider', :git => 'https://github.com/yonat/MultiSlider.git', :branch => 'swiftui'
```

**Comment by JKim0119** [comment]
Didn't know you could do that with pods. Thank you!
