### ISSUE TITLE
Initial thumb movement skips values

### ISSUE THREAD

**Issue by sophiagatliff** [yonat/MultiSlider#63]
**Description of the problem:**
Initial thumb movement skips 1-2 values when set to an increment of 1. (so if you start at 18, it jumps to 20 or 21 instead of going to 19).

**Minimal project that reproduces the problem (so I'll be able to figure out how to fix it):**
https://github.com/sophiagatliff/multisliderbug

You'll have to `pod init` and `pod install` MultiSlider. Don't know how .gitignore works with Xcode source controlled projects. Everything else works. (Oh and its iOS 13.0 as a target).

**Comment by sophiagatliff** [comment]
IDK how to make a pull request, but I fixed it.

Change:
```let translationSnapped = panGesture.translation(in: slideView).coordinate(in: orientation).rounded(stepSizeInView)```
To
```let translationSnapped = panGesture.translation(in: slideView).coordinate(in: orientation).rounded()```

You don't need the step size in the view, just a rounded translation. It works fine then.

**Comment by yonat** [comment]
Thanks for linking to an actual project demonstrating the problem, this helps greatly.
