### ISSUE TITLE
SwiftUI MultiSlider - Changing label font

### ISSUE THREAD

**Issue by JKim0119** [yonat/MultiSlider#69]
**Description:**
Using your swiftui slider for my project and was wondering if you'd be able to add the ability to choose the font for the labels.

Wondering if it would be possible to add the ability to change the size of the thumbs (the circles). 

Thank you!

**Comment by JKim0119** [comment]
Also wondering if there is a way to do the outerTrackColor for only one side. I'd like to be consistent with my design and use your multislider for a single slider as well but I have the same color for both sides and would prefer it to be on just one side like a normal slider.

So this:
![image](https://user-images.githubusercontent.com/30351434/103490594-8c7ecd00-4de2-11eb-88e2-d9cfa8aab0cd.png)

To be like this:
![image](https://user-images.githubusercontent.com/30351434/103490600-999bbc00-4de2-11eb-9c41-689cb0ff7282.png)


Sorry for having so many requests. Love the work though. Thanks a lot!

**Comment by yonat** [comment]
All good suggestions! Though only one is currently implemented: You can change the `thumbImage` to an image of a different size.

I'll see if I can get to implementing the other suggestions. If not - feel free to submit a PR.

**Comment by yonat** [comment]
I added `valueLabelFont` to the latest release, and made all these properties accessible in SwiftUI. Enjoy!

**Comment by JKim0119** [comment]
Wow that was so fast. Thanks for adding the valueLabelFont feature!

Could you explain what you mean by the "outerTrackColor will color the track above the single thumb"? The first image I showed only displays a single thumb but the outerTrackColor colored both sides of the single thumb. Maybe I'm using the single thumb incorrectly. Here is my code for it

```
MultiValueSlider(
    value: self.$radius,
    minimumValue: 1,
    maximumValue: 25,
    snapStepSize: 1,
    valueLabelPosition: .bottom,
    orientation: .horizontal,
    outerTrackColor: UIColor(Color("gray")),
    trackWidth: 8
)
.accentColor(Color("cyan"))
```

The radius value is just a single value in the CGFloat array. Thanks once again!

**Comment by JKim0119** [comment]
Just kidding, I guess the outer track thing got fixed too. Thanks a ton once again!
