### ISSUE TITLE
"Cannot find 'MultiValueSlider' in scope"

### ISSUE THREAD

**Issue by prizm-app** [yonat/MultiSlider#70]
I installed MultiSlider using `pod 'MultiSlider'`

I imported MultiSlider using `import MultiSlider`

Yet when I try to use `MultiValueSlider()` xcode says it cannot find it in scope. Must I install the swiftui branch specifically using cocoapods or is there another issue I am not seeing?

**Comment by prizm-app** [comment]
I figured it out lol

**Comment by yonat** [comment]
Yes, use the `swiftui` branch.
