### ISSUE TITLE
Unable to set "Custom Class" to Multislider

### ISSUE THREAD

**Issue by ddownn** [yonat/MultiSlider#72]
Hello, I have added the MultiSlider package to an iOS project, and in the Target, I added it also.

I get no errors when I declare this in the ViewController: @IBOutlet var slider: MultiSlider!

But when I add a slider to the storyboard and try to enter Multislider for the custom class, it doesn't allow it.

What could I be doing wrong?

**Comment by yonat** [comment]
What do you mean by "doesn't allow it"? What do you do, and what happens then?

The best way  for me to  understand the problem, is if you create a minimal project that reproduces this problem, create a github project with its code, and link to it here. (See https://ootips.org/yonat/repex/)

**Comment by ddownn** [comment]
I type in MultiSlider in the class field and press enter, Mac plays a system sound and clears what I typed in so I end up with an empty class field in the Custom Class section.

**Comment by briend** [comment]
I had the same issue. I think this is because MultiSlider does not inherit from `UISlider`; it inherits `UIControl`, which in turn inherits `UIView`.  So, just add a View (`UIView`) to your storyboard and then you can type in `MultiSlider` in the Custom Class box.
