### ISSUE TITLE
If I set value two times, the second time doesn't take into account and the thumbs don't change position.

### ISSUE THREAD

**Issue by gonzalobarrios** [yonat/MultiSlider#73]
**Description of the problem:**
After the view is created and all is set up, If I want to change the value of the slider it does not change using 2 thumbs.

if I change the value to:
 slider.value = [22, 38]

It takes them, but it does not change graphically (thumb doesn't change position).
 
 Note*: the minimalValue is 18 and maximumValue is 80 for this case.
 
Any thoughts on this?

**Comment by yonat** [comment]
I'll need running code to help with this...
Please create a minimal project that reproduces this problem, create a github project with its code, and link to it here. (See https://ootips.org/yonat/repex/)

**Comment by varuntotlani** [comment]
Have the same issue. Anyone got a solution here? 

slider.value = [22, 38]

After manually setting the values, both the thumbs does not move to passed values, but moves to minumum value of slider.

**Comment by yonat** [comment]
Hi @varuntotlani,
Please create a minimal project that reproduces this problem, create a github project with its code, and link to it here. (See https://ootips.org/yonat/repex/)

**Comment by varuntotlani** [comment]
so it goes this way, I had a vertical slider, I needed maximum value at bottom of the slider and minimum value at top of the slider, which wasn't supported with multislider. I tried a work around which did not worked, so posted the comment. 

However I now have found a different workaround.

Thank you for the awesome library.
