### ISSUE TITLE
Set values from preferences...

### ISSUE THREAD

**Issue by birkyboydesign** [yonat/MultiSlider#79]
Hello, thanks for this SPM.
In my app I m saving the current value of the slider at a Int in cloudKit to sync between devices.
When I try to set the value for the sliders nothing happens.
Am I doing it right?

 let slider: MultiSlider = {
        let slider = MultiSlider()
        slider.hasRoundTrackEnds = true
        slider.orientation = .horizontal
        slider.minimumValue = 0
        slider.maximumValue = 9
        slider.value = [2, 6]
        slider.snapStepSize = 1
// ... rest of the subview 
}

// Configure Prefs
func configureRange(with range: [Int]) {
        slider.value = range.map({ CGFloat($0) })
}

Thank you

**Comment by umerirfan26** [comment]
@birkyboydesign how you solved this issue?
@yonat same issue for me
