### ISSUE TITLE
Swift+Sweeter.swift makes bug that can't use UISlider().value

### ISSUE THREAD

**Issue by icopyx** [yonat/MultiSlider#81]
SPM and Pod All same  need SwiftSweeter
and that makes can't use UISlider.value 

value return UISlider?  so I can't build this.
![스크린샷 2022-03-11 오전 2 30 24](https://user-images.githubusercontent.com/8281485/157721627-32f30d96-63d7-4754-91c3-885b0b6f4ed9.png)

**Comment by yonat** [comment]
I'll need running code to help with this...
Please create a minimal project that reproduces this problem, create a github project with its code, and link to it here. (See https://ootips.org/yonat/repex/)
