### ISSUE TITLE
Delegate method to detect when both thumbs overlap

### ISSUE THREAD

**Issue by lsamaria** [yonat/MultiSlider#84]
I haven't been able to get the right thumb to appear to test this out so maybe this already exists. Is there anyway to to detect when both thumbs overlap? If not, would you be able to create a delegate method to detect when they meet. Maybe within a certain range being the right side of the left thumb intersects with the left side of the right thumb?

I added a link and some code below to help you out if you need it.

I needed to do something similar with a collectionView. I asked this question and I got a fantastic response that I use in 2 different projects https://stackoverflow.com/a/68109661/4833705. It works perfectly. I'm not sure how it would work with a slider though.

In a separate project I have to track the thumbBall of 2 different regular UISliders but of course each slider only has 1 trackball on top of it. Yours would probably be a bit more complicated because there are 2 balls on 1 slider.

```
func trackThumbBallPostiton() {

    let trackRect = slider.trackRect(forBounds: slider.bounds)

    let thumbRect = slider.thumbRect(forBounds: slider.bounds,
                                           trackRect: trackRect,
                                           value: slider.value)

    let ballRect = slider.convert(thumbRect, to: self.view)
        
    let centerX = ballRect.midX
    let centerY = ballRect.midY
    let width = ballRect.size.width
    let height = ballRect.size.Height
        
    // In my project I have  a label that follows the trackBall as the user scrolls. I use the centerX or centerY value to track it depending on if the slider is horizontal or vertical.

    // for a horizontal slider maybe you can use something like this
    let rightSideOfLeftSlider = centerX + (width / 2)

    // for a veritcal slider maybe you can use something like this
    let bottomOfTopSlider = centerY + (height / 2)
}
```

I also use this to track a regular UIView in a separate project:

 ```
func track(_ element: UIView) {

    guard let window = UIApplication.shared.windows.first(where: \.isKeyWindow) else { return }

    let elementFrameInWindow: CGRect = element.convert(element.frame, to: window)

    guard let globalPoint: CGPoint = element.superview?.convert(element.frame.origin, to: nil) else { return } /// https://stackoverflow.com/a/41988249/4833705

    let elementHeight = elementFrameInWindow.height
    let elementWidth = elementFrameInWindow.width

    let centerX = globalPoint.x

    let rightSideOfElement = centerX + elementWidth / 2
}
```

**Comment by yonat** [comment]
What do you plan to do when the sliders are overlap?
Could the property `distanceBetweenThumbs` be used achieve this?

**Comment by lsamaria** [comment]
I tried to use that property, it didn't work out. I'm fine with comparing my leftThumbValue and rightThumbValues. Thanks.
