### ISSUE TITLE
How to decrease spacing between slider thumb and value label?

### ISSUE THREAD

**Issue by darshit-blueera** [yonat/MultiSlider#87]
I want decrease the spacing between slider thumb and value label.

![Screen shot](https://user-images.githubusercontent.com/89004806/164910335-3e5364d0-1f06-4903-a31b-f98d65eff798.png)

**Comment by yonat** [comment]
I suggest you first check on a real device, and see if there's still space between your finger and the value label. Otherwise, decreasing the spacing will cause the label to be covered by the finger.

**Comment by darshit-blueera** [comment]
I have checked on real device. Just wanted to reduce it like say 5 pixels to look more connected with the thumb rather then floating.

**Comment by yonat** [comment]
Try this:

```swift
slider.valueLabelPosition = .firstBaseline
```

**Comment by darshit-blueera** [comment]
It works. Thanks for your help.
