### ISSUE TITLE
Seems that .accentColor is not working

### ISSUE THREAD

**Issue by Fl34r** [yonat/MultiSlider#92]
**Description of the problem:**
Using .accentColor(.red) modifier on the MultiValueSlider still shows a system blue track

**Minimal project that reproduces the problem (so I'll be able to figure out how to fix it):**
import SwiftUI
import MultiSlider

struct SliderView: View {
    @ObservedObject var viewModel: SliderViewModel

    var body: some View {
        MultiValueSlider(
            value: $viewModel.valueBounds,
            minimumValue: CGFloat(viewModel.range.lowerBound),
            maximumValue: CGFloat(viewModel.range.upperBound),
            snapStepSize: CGFloat(viewModel.stepSize),
            valueLabelPosition: .top,
            orientation: .horizontal,
            outerTrackColor: .gray,
            valueLabelColor: .blue,
            showsThumbImageShadow: true,
            trackWidth: 4.0,
            hasRoundTrackEnds: true,
            keepsDistanceBetweenThumbs: true
        )
        .accentColor(.red)
        .padding(.top, 8)
    }
}

**Comment by yonat** [comment]
Thanks for reporting, fixed in 1.13.2.

**Comment by Fl34r** [comment]
Thanks!
