### ISSUE TITLE
Center Thumb on Track End

### ISSUE THREAD

**Issue by skajake** [yonat/MultiSlider#93]
I would like to center the thumb on the ends of the track when you drag them to the ends.  In other words, when you have the maximum value selected, the center of the thumb should be aligned to the maximum value of the track.

is there a way to accomplish this?

**Comment by yonat** [comment]
Hmm, this deviates from the standard behavior of `UISlider`, which I tried to mimic. The library doesn't support this.

**Comment by yonat** [comment]
Added `centerThumbOnTrackEnd` in version 2.0.0.
