### ISSUE TITLE
Opposing Value Label Positions

### ISSUE THREAD

**Issue by emtjoshhart** [yonat/MultiSlider#97]
**Description:**
For a horizontal layout, value labels can collide and cause overlap when valueLabelPosition is .top or .bottom.  I've been using your library for 3+ years, it's been super solid and amazing.  Thank you sooo very much!
![IMG_8542](https://github.com/yonat/MultiSlider/assets/10798600/9dc10bb4-d893-43c7-9289-d9c6d910e1ff)

**Problems I encountered when trying to implement this myself:**
I didn't implement any changes because I am using SPM, but perhaps a boolean indicating the opposite of the valueLabelPosition, like:

`/// Every other value label will show opposite of the value label position.  If you set valueLabelPosition to .top, the second value label position would be bottom, if you set valueLabelPosition to .leading, the second value label position would be .trailing.`

`@IBInspectable open dynamic var inverseValueLabelPositioning: Bool = false {
    didSet {
        updateAllValueLabels()
    }
}`

or perhaps creating a valueLabelPositions array where they can be defined.

`slider.valueLabelPositions = [.top, .bottom]`

**Comment by yonat** [comment]
Nice idea!

I’m currently on vacation, but will take a shot at it in a cot of weeks.
